version: '3.5'

services:
  db: # Banco de dados
    image: postgres
    container_name: rinha_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rinha_user
      POSTGRES_PASSWORD: rinha_password
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
  
  nginx: # Load Balancer
    image: nginx:latest
    container_name: rinha_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    # depends_on:
    #   - api1
    #   - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'